# Generated by Django 4.0.2 on 2022-02-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0003_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
