# Generated by Django 4.0.2 on 2022-02-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0005_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='session_data',
            field=models.JSONField(default={}),
        ),
    ]
