# Generated by Django 4.0.2 on 2022-02-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0006_usersubscription_session_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='session_data',
            field=models.JSONField(default=dict),
        ),
    ]
