# Generated by Django 4.0.2 on 2022-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0007_alter_usersubscription_session_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='session_data',
            new_name='transaction_data',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=100),
        ),
    ]
