# Generated by Django 4.0.2 on 2022-02-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscription', '0008_rename_session_data_usersubscription_transaction_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='transaction_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
